apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: SERVICE_NAME
          image: gcr.io/pelagic-diorama-442307-c0/orderservice:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: microservices-config