steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/pelagic-diorama-442307-c0/orderservice:v1, '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/pelagic-diorama-442307-c0/orderservice:v1']

  # Deploy container image to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=kubernetes
      - --location=${_REGION}
      - --cluster=${_CLUSTER_NAME}

substitutions:
  _SERVICE_NAME: microservices-deployer
  _REGION: us-central1
  _CLUSTER_NAME: new-cluster-1

images:
  - 'gcr.io/pelagic-diorama-442307-c0/orderservice:v1'