name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      # Build each service with Maven
      - name: Build API Gateway
        working-directory: ./ApiGateway
        run: mvn clean package -DskipTests

      - name: Build Order Service
        working-directory: ./OrderService
        run: mvn clean package -DskipTests

      - name: Build Product Service
        working-directory: ./ProductService
        run: mvn clean package -DskipTests

      - name: Build User Service
        working-directory: ./UserService
        run: mvn clean package -DskipTests

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Set up Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: 'latest'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          docker-compose version

      # Authenticate Docker with Google Cloud
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Build and push images
      - name: Build and Push Docker Images
        run: |
          echo "Building and pushing Docker images"
          docker-compose build
          docker-compose push