name: CI/CD Pipeline

on:
  push:
    branches:
      - new-branch-name

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build Java applications
      - name: Build with Maven
        run: |
          cd ApiGateway && ./mvnw clean package -DskipTests
          cd ../OrderService && ./mvnw clean package -DskipTests
          cd ../ProductService && ./mvnw clean package -DskipTests
          cd ../UserService && ./mvnw clean package -DskipTests

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push images to Docker Hub
      - name: Build and Push Docker Images
        run: |
          # Build images
          docker compose build
          
          # Tag images for Docker Hub
          docker tag api-gateway:latest ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
          docker tag order-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
          docker tag product-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
          docker tag user-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
          
          # Push images to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest