name: CI/CD Pipeline

on:
  push:
    branches:
      - new-branch-name

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Generate Maven Wrapper and Build Projects
      - name: Build with Maven
        run: |
          # Generate Maven Wrapper and build ApiGateway
          cd ApiGateway
          mvn -N io.takari:maven:wrapper
          ./mvnw clean package -DskipTests
          
          # Generate Maven Wrapper and build OrderService
          cd ../OrderService
          mvn -N io.takari:maven:wrapper
          ./mvnw clean package -DskipTests
          
          # Generate Maven Wrapper and build ProductService
          cd ../ProductService
          mvn -N io.takari:maven:wrapper
          ./mvnw clean package -DskipTests
          
          # Generate Maven Wrapper and build UserService
          cd ../UserService
          mvn -N io.takari:maven:wrapper
          ./mvnw clean package -DskipTests

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push images to Docker Hub
      - name: Build and Push Docker Images
        run: |
          # Build images
          docker compose build
          
          # Tag images for Docker Hub
          docker tag api-gateway:latest ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
          docker tag order-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
          docker tag product-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
          docker tag user-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
          
          # Push images to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest