name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build and push images
      - name: Build and Push Docker Images
        run: |
          echo "Building and pushing Docker images"
          gcloud auth configure-docker
          docker-compose build
          docker-compose push

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Set up Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Authenticate kubectl
      - name: Authenticate kubectl
        run: |
          gcloud container clusters get-credentials [CLUSTER_NAME] --region [REGION]

      # Deploy Kubernetes manifests
      - name: Deploy to GKE
        run: |
          kubectl apply -f ApiGateway/kubernetes
          kubectl apply -f OrderService/kubernetes
          kubectl apply -f ProductService/kubernetes
          kubectl apply -f UserService/kubernetes
